---
title: "R Notebook"
output: html_notebook
---

```{r}

library(Seurat)
library(Matrix)
library(Matrix.utils)

data_cb<-Read10X(data.dir = "/home/fgao/Data_single_cell/Cai_Lab/GSE165371_cb_adult_mouse", gene.column=1)

sample_cb <- CreateSeuratObject(counts = data_cb, project = "CB")
meta<-read.csv("/home/fgao/Data_single_cell/Cai_Lab/GSE165371_cb_adult_mouse/cerebellum-atlas-analysis/data/cluster_metadata.csv", header=T)
rep<-do.call(rbind, strsplit(colnames(sample_cb), "_"))

sample_cb$sample<-paste(rep[,1], rep[,2], sep="_")
sample_cb$cluster<-meta$cluster
Idents(sample_cb)<-meta$region

# Replicate based analysis for selected samples ("VIIa_F002", "VIIa_M002", "VIIa_M006", "VIIb_F002", "VIIb_M002", "VIIb_M006", "VIIc_M002", "VIId_M002")
sample_cb_sel<-subset(sample_cb, subset = sample == c("VIIa_F002", "VIIa_M002", "VIIa_M006", "VIIb_F002", "VIIb_M002", "VIIb_M006", "VIIc_M002", "VIId_M002"))


sample_cb_sel_mtx<-sample_cb_sel@assays$RNA@counts 
#group_sel<-as.character(sample_cb_sel$sample)
sample_cb_sel_mtx_t<-data.frame(t(sample_cb_sel_mtx))
sample_cb_sel_mtx_t$sample<-as.character(sample_cb_sel$sample)
sample_cb_sel_mtx_t$cluster<-as.character(sample_cb_sel$cluster)

# aggregate by two factors "sample", "cluster"
sample_cb_sel_mtx.agg <- aggregate(sample_cb_sel_mtx_t[1:nrow(sample_cb_sel_mtx)], by=list(sample_cb_sel_mtx_t$sample, sample_cb_sel_mtx_t$cluster), sum)

sample_cb_sel_agg <- t(sample_cb_sel_mtx.agg[,c(3:ncol(sample_cb_sel_mtx.agg))])
#colnames(sample_cb_sel_agg) <- sample_cb_sel_mtx.agg$group_sel

meta_cb_sel<-data.frame(ID=sample_cb_sel_mtx.agg$Group.1, CLUSTER=sample_cb_sel_mtx.agg$Group.2)

# "Granule", "Bergmann", "MLI1", and "Purkinje" DEG analysis

data_path<-"/home/fgao/Data_single_cell/Cai_Lab/GSE165371_cb_adult_mouse/"
library(DESeq2)  
dds1 <- DESeqDataSetFromMatrix(countData=sample_cb_sel_agg, colData=meta_cb_sel, design=~CLUSTER)
dds1 <- DESeq(dds1)

res1 <- results(dds1, contrast = c("CLUSTER", "Bergmann", "MLI1"))
res1 <- res1[order(res1$padj),]
res1_sig = subset(res1, padj<0.05)
write.table(res1, file = paste(data_path, "deg_deseq2_ensemble_Bergmann_MLI1.txt", sep=""), quote=F, sep="\t")
write.table(res1_sig, file = paste(data_path, "deg_deseq2_ensemble_Bergmann_MLI1_sig.txt", sep=""), quote=F, sep="\t")

res1 <- results(dds1, contrast = c("CLUSTER", "Bergmann", "Purkinje"))
res1 <- res1[order(res1$padj),]
res1_sig = subset(res1, padj<0.05)
write.table(res1, file = paste(data_path, "deg_deseq2_ensemble_Bergmann_Purkinje.txt", sep=""), quote=F, sep="\t")
write.table(res1_sig, file = paste(data_path, "deg_deseq2_ensemble_Bergmann_Purkinje_sig.txt", sep=""), quote=F, sep="\t")

res1 <- results(dds1, contrast = c("CLUSTER", "Granule", "Bergmann"))
res1 <- res1[order(res1$padj),]
res1_sig = subset(res1, padj<0.05)
write.table(res1, file = paste(data_path, "deg_deseq2_ensemble_Granule_Bergmann.txt", sep=""), quote=F, sep="\t")
write.table(res1_sig, file = paste(data_path, "deg_deseq2_ensemble_Granule_Bergmann_sig.txt", sep=""), quote=F, sep="\t")

res1 <- results(dds1, contrast = c("CLUSTER", "Granule", "MLI1"))
res1 <- res1[order(res1$padj),]
res1_sig = subset(res1, padj<0.05)
write.table(res1, file = paste(data_path, "deg_deseq2_ensemble_Granule_MLI1.txt", sep=""), quote=F, sep="\t")
write.table(res1_sig, file = paste(data_path, "deg_deseq2_ensemble_Granule_MLI1_sig.txt", sep=""), quote=F, sep="\t")

res1 <- results(dds1, contrast = c("CLUSTER", "Granule", "Purkinje"))
res1 <- res1[order(res1$padj),]
res1_sig = subset(res1, padj<0.05)
write.table(res1, file = paste(data_path, "deg_deseq2_ensemble_Granule_Purkinje.txt", sep=""), quote=F, sep="\t")
write.table(res1_sig, file = paste(data_path, "deg_deseq2_ensemble_Granule_Purkinje_sig.txt", sep=""), quote=F, sep="\t")

res1 <- results(dds1, contrast = c("CLUSTER", "MLI1", "Purkinje"))
res1 <- res1[order(res1$padj),]
res1_sig = subset(res1, padj<0.05)
write.table(res1, file = paste(data_path, "deg_deseq2_ensemble_MLI1_Purkinje.txt", sep=""), quote=F, sep="\t")
write.table(res1_sig, file = paste(data_path, "deg_deseq2_ensemble_MLI1_Purkinje_sig.txt", sep=""), quote=F, sep="\t")

res1 <- results(dds1, contrast = c("CLUSTER", "MLI1", "MLI2"))
res1 <- res1[order(res1$padj),]
res1_sig = subset(res1, padj<0.05)
write.table(res1, file = paste(data_path, "deg_deseq2_ensemble_MLI1_MLI2.txt", sep=""), quote=F, sep="\t")
write.table(res1_sig, file = paste(data_path, "deg_deseq2_ensemble_MLI1_MLI2_sig.txt", sep=""), quote=F, sep="\t")

res1 <- results(dds1, contrast = c("CLUSTER", "MLI1", "PLI"))
res1 <- res1[order(res1$padj),]
res1_sig = subset(res1, padj<0.05)
write.table(res1, file = paste(data_path, "deg_deseq2_ensemble_MLI1_PLI.txt", sep=""), quote=F, sep="\t")
write.table(res1_sig, file = paste(data_path, "deg_deseq2_ensemble_MLI1_PLI_sig.txt", sep=""), quote=F, sep="\t")

# generate noramlized count matrix
dds1 <- estimateSizeFactors(dds1)
normalized_counts <- counts(dds1, normalized=TRUE)
write.table(rbind(t(meta_cb_sel), normalized_counts), file= paste(data_path, "ensembl_gene_counts_normalized.txt", sep=""), sep="\t", quote=F, col.names=F)

```

```{r}

# MLI2 and PLI clusters merge to MLI2_PLI cluster
sample_cb_sel_mtx_t2<-sample_cb_sel_mtx_t
sample_cb_sel_mtx_t2[sample_cb_sel_mtx_t2 == "MLI2" | sample_cb_sel_mtx_t2 == "PLI"] <- "MLI2_PLI"

# aggregate by two factors "sample", "cluster"
sample_cb_sel_mtx.agg2 <- aggregate(sample_cb_sel_mtx_t2[1:nrow(sample_cb_sel_mtx)], by=list(sample_cb_sel_mtx_t2$sample, sample_cb_sel_mtx_t2$cluster), sum)

sample_cb_sel_agg2 <- t(sample_cb_sel_mtx.agg2[,c(3:ncol(sample_cb_sel_mtx.agg2))])

meta_cb_sel2<-data.frame(ID=sample_cb_sel_mtx.agg2$Group.1, CLUSTER=sample_cb_sel_mtx.agg2$Group.2)

dds2 <- DESeqDataSetFromMatrix(countData=sample_cb_sel_agg2, colData=meta_cb_sel2, design=~CLUSTER)
dds2 <- DESeq(dds2)

res2 <- results(dds2, contrast = c("CLUSTER", "MLI1", "MLI2_PLI"))
res2 <- res2[order(res2$padj),]
res2_sig = subset(res2, padj<0.05)
write.table(res2, file = paste(data_path, "deg_deseq2_ensemble_MLI1_MLI2-PLI.txt", sep=""), quote=F, sep="\t")
write.table(res2_sig, file = paste(data_path, "deg_deseq2_ensemble_MLI1_MLI2-PLI_sig.txt", sep=""), quote=F, sep="\t")

```
