---
title: "R Notebook"
output: html_notebook
---

```{r}

data_path<-"/home/fgao/Data_single_cell/Cai_Lab/DEG_cell_lines/"

library(Seurat)
library(Matrix)
library(Matrix.utils)

#aggregate by factor "rep"
data_es<-read.csv(paste(data_path, "110922_formated_E14_rep1_rep2_intron_count.csv", sep=""), header=T, row.names=1, check.names = FALSE)
data_es.rep<-aggregate(data_es[, c(5:ncol(data_es))], by=list(data_es$rep), sum)

data_nm<-read.csv(paste(data_path, "110922_formated_NMuMG_rep1_intron_count.csv", sep=""), header=T, row.names=1, check.names = FALSE)
data_nm.rep<-aggregate(data_nm[, c(3:ncol(data_nm))], by=list(data_nm$rep), sum)
  
sample.rep<-merge(t(data_es.rep[,-1]), t(data_nm.rep[,-1]), by=0)
rownames(sample.rep)<-sample.rep$Row.names
sample.rep<-sample.rep[,-1]
colnames(sample.rep)<-c("ES1", "ES2", "NM1")
write.table(t(sample.rep), file=paste(data_path, "ensembl_gene_counts_rep.txt", sep=""), quote=F, sep="\t")

library(DESeq2)  
meta_rep<-data.frame(ID=c("ES1", "ES2", "NM1"), GROUP=c("ES", "ES", "NM"))
dds1 <- DESeqDataSetFromMatrix(countData=sample.rep, colData=meta_rep, design=~GROUP)
dds1 <- DESeq(dds1)

res1 <- results(dds1, contrast = c("GROUP", "ES", "NM"))
res1 <- res1[order(res1$padj),]
res1_sig = subset(res1, padj<0.05)
write.table(res1, file = paste(data_path, "deg_deseq2_ensemble_ES_NM_rep.txt", sep=""), quote=F, sep="\t")
write.table(res1_sig, file = paste(data_path, "deg_deseq2_ensemble_ES_NM_sig_rep.txt", sep=""), quote=F, sep="\t")


# generate noramlized count matrix
dds1 <- estimateSizeFactors(dds1)
normalized_counts <- counts(dds1, normalized=TRUE)
write.table(rbind(t(meta_rep), normalized_counts), file= paste(data_path, "ensembl_gene_counts_normalized_rep.txt", sep=""), sep="\t", quote=F, col.names=F)

```


# mRNA state
```{r}

#aggregate by factor "mRNA_states", "rep"
#data_es$state<-data_es$mRNA_states
#data_es$state[data_es$state == 0] <- "S0"
#data_es$state[data_es$state == 1] <- "S1"
#data_es$state[data_es$state == 2] <- "S2"
#data_es$state[data_es$state == 3] <- "S3"
#data_es$state[data_es$state == 4] <- "S4"

data_path<-"/home/fgao/Data_single_cell/Cai_Lab/DEG_cell_lines/"

library(Seurat)
library(Matrix)
library(Matrix.utils)

data_es<-read.csv(paste(data_path, "110922_formated_E14_rep1_rep2_intron_count.csv", sep=""), header=T, row.names=1, check.names = FALSE)
mtx_es<-t(data_es[, c(5:ncol(data_es))])
colnames(mtx_es)<-data_es$cell_id
  
es<-CreateSeuratObject(mtx_es, project = "ES")
es<-NormalizeData(es, normalization.method = "LogNormalize", scale.factor = 10000)
es$mRNA_states<-data_es$mRNA_states
es$Cell_cycle<-data_es$Cell_cycle

deg_mRNA_states <- FindMarkers(es, ident.1 = 0, ident.2 = 3, group.by = "mRNA_states", logfc.threshold = 0, min.pct = 0.01, test.use = "MAST")
deg_mRNA_states_sig <- subset(deg_mRNA_states, p_val_adj<0.05)
dim(deg_mRNA_states_sig)


#es<-ScaleData(es, verbose = FALSE)

#data_es.state<-aggregate(data_es[, c(5:(ncol(data_es)-1))], by=list(data_es$rep, data_es$state), sum)
#sample.state<-t(data_es.state[,-2])
#meta_state<-data.frame(ID=data_es.state$Group.1, CLUSTER=data_es.state$Group.2)
#colnames(sample.state)<-meta_state$CLUSTER
#write.table(t(sample.state), file=paste(data_path, "ensembl_gene_counts_state.txt", sep=""), quote=F, sep="\t")
#dds1 <- DESeqDataSetFromMatrix(countData=sample.state, colData=meta_state, design=~CLUSTER)
#dds1 <- DESeq(dds1)

#res1 <- results(dds1, contrast = c("CLUSTER", "S0", "S3"))
#res1 <- res1[order(res1$padj),]
#res1_sig = subset(res1, padj<0.05)
#write.table(res1, file = paste(data_path, "deg_deseq2_ensemble_S0_S3_state.txt", sep=""), quote=F, sep="\t")
#write.table(res1_sig, file = paste(data_path, "deg_deseq2_ensemble_S0_S3_sig_state.txt", sep=""), quote=F, sep="\t")


# generate noramlized count matrix
#dds1 <- estimateSizeFactors(dds1)
#normalized_counts <- counts(dds1, normalized=TRUE)
#write.table(rbind(t(meta_state), normalized_counts), file= paste(data_path, "ensembl_gene_counts_normalized_state.txt", sep=""), sep="\t", quote=F, col.names=F)

```


#cell cycle
```{r}

#aggregate by factor "Cell_cycle", "rep"
data_es$cycle<-data_es$Cell_cycle
data_es$cycle[data_es$cycle == 0] <- "S0"
data_es$cycle[data_es$cycle == 1] <- "S12"
data_es$cycle[data_es$cycle == 2] <- "S12"
data_es$cycle[data_es$cycle == 3] <- "S3"

data_es.cycle<-aggregate(data_es[, c(5:(ncol(data_es)-2))], by=list(data_es$rep, data_es$cycle), sum)
sample.cycle<-t(data_es.cycle[,-2])

meta_cycle<-data.frame(ID=data_es.cycle$Group.1, CLUSTER=data_es.cycle$Group.2)
colnames(sample.cycle)<-meta_cycle$CLUSTER

write.table(t(sample.cycle), file=paste(data_path, "ensembl_gene_counts_cycle.txt", sep=""), quote=F, sep="\t")

dds1 <- DESeqDataSetFromMatrix(countData=sample.cycle, colData=meta_cycle, design=~CLUSTER)
dds1 <- DESeq(dds1)

res1 <- results(dds1, contrast = c("CLUSTER", "S12", "S3"))
res1 <- res1[order(res1$padj),]
res1_sig = subset(res1, padj<0.05)
write.table(res1, file = paste(data_path, "deg_deseq2_ensemble_S12_S3_cycle.txt", sep=""), quote=F, sep="\t")
write.table(res1_sig, file = paste(data_path, "deg_deseq2_ensemble_S12_S3_sig_cycle.txt", sep=""), quote=F, sep="\t")


# generate noramlized count matrix
dds1 <- estimateSizeFactors(dds1)
normalized_counts <- counts(dds1, normalized=TRUE)
write.table(rbind(t(meta_cycle), normalized_counts), file= paste(data_path, "ensembl_gene_counts_normalized_cycle.txt", sep=""), sep="\t", quote=F, col.names=F)

```

